# Generated by Django 4.2.11 on 2024-04-05 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0002_alter_takes_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='credit',
            field=models.IntegerField(null=True),
        ),
    ]
