# Generated by Django 4.2.11 on 2024-04-05 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0003_course_credit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='advisor',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='classroom',
            field=models.CharField(default='', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='day',
            field=models.IntegerField(null=True),
        ),
    ]
