# Generated by Django 4.2.11 on 2024-04-12 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0005_alter_takes_final_grade_alter_takes_middle_grade'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notice',
        ),
    ]
