# Generated by Django 4.2.11 on 2024-04-12 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.CharField(max_length=100, null=True)),
                ('title', models.CharField(max_length=100, null=True)),
                ('url', models.URLField(null=True)),
                ('writer', models.CharField(max_length=100, null=True)),
                ('date', models.DateField(null=True)),
            ],
        ),
    ]
