# Generated by Django 4.2.11 on 2024-05-11 04:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='mod',
        ),
        migrations.AddField(
            model_name='post',
            name='board',
            field=models.CharField(default='free', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post_pictures/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='upvote',
            field=models.ManyToManyField(blank=True, null=True, related_name='upvoted_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='view',
            field=models.ManyToManyField(blank=True, null=True, related_name='viewed_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='view_num',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
