# Generated by Django 4.2.11 on 2024-05-12 00:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0004_alter_post_view'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='upvote',
            new_name='upvotes',
        ),
        migrations.RemoveField(
            model_name='post',
            name='upvote_num',
        ),
        migrations.AddField(
            model_name='post',
            name='downvotes',
            field=models.ManyToManyField(blank=True, related_name='downvoted_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
