# Generated by Django 4.2.11 on 2024-05-12 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_rename_upvote_post_upvotes_remove_post_upvote_num_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='view_num',
            new_name='view_count',
        ),
        migrations.RemoveField(
            model_name='post',
            name='view',
        ),
    ]
