# Generated by Django 4.2.11 on 2024-05-01 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0002_facility_used_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='abbr',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
