# Generated by Django 4.2.11 on 2024-05-10 16:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0003_building_abbr'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('items', models.JSONField(default=list)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='maps.building')),
            ],
        ),
    ]
