# Generated by Django 4.2.11 on 2024-05-10 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0004_menu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='items',
        ),
        migrations.AddField(
            model_name='menu',
            name='items_by_corner',
            field=models.JSONField(default=dict),
        ),
    ]
