# Generated by Django 4.2.11 on 2024-05-10 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0005_remove_menu_items_menu_items_by_corner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='maps.facility'),
        ),
    ]
