# Generated by Django 4.2.11 on 2024-05-10 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0008_alter_menu_building'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='building',
            new_name='facility',
        ),
    ]
