# Generated by Django 4.2.11 on 2024-05-15 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0009_rename_building_menu_facility'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=50)),
                ('trav_time', models.IntegerField()),
                ('place', models.CharField(max_length=50)),
                ('avg_Price', models.IntegerField()),
                ('times', models.JSONField()),
                ('image', models.URLField()),
                ('NaverMap', models.URLField()),
                ('OneLiner', models.TextField()),
                ('tags', models.ManyToManyField(related_name='restaurants', to='maps.tag')),
            ],
        ),
    ]
