# Generated by Django 4.2.11 on 2024-05-16 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0010_tag_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='NaverMap',
            field=models.URLField(max_length=512),
        ),
    ]
