// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBeMK868pIiIrHTCQlz4juJwIwE-rpZiM',
    appId: '1:131941295256:web:f8bb38997918f7885d1ced',
    messagingSenderId: '131941295256',
    projectId: 'soganggpt-8a6aa',
    authDomain: 'soganggpt-8a6aa.firebaseapp.com',
    storageBucket: 'soganggpt-8a6aa.appspot.com',
    measurementId: 'G-DF1HB43ZZJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCL6CHevxKGqFi1te3ziaEwuzIz0U9btN8',
    appId: '1:131941295256:android:47330c7b6def0e1e5d1ced',
    messagingSenderId: '131941295256',
    projectId: 'soganggpt-8a6aa',
    storageBucket: 'soganggpt-8a6aa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjEo8_6R5r8kp8Sn5wSX4FPlTPwXmetnA',
    appId: '1:131941295256:ios:38d29698db085e855d1ced',
    messagingSenderId: '131941295256',
    projectId: 'soganggpt-8a6aa',
    storageBucket: 'soganggpt-8a6aa.appspot.com',
    iosBundleId: 'com.soganglink.soganglink',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjEo8_6R5r8kp8Sn5wSX4FPlTPwXmetnA',
    appId: '1:131941295256:ios:38d29698db085e855d1ced',
    messagingSenderId: '131941295256',
    projectId: 'soganggpt-8a6aa',
    storageBucket: 'soganggpt-8a6aa.appspot.com',
    iosBundleId: 'com.soganglink.soganglink',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBeMK868pIiIrHTCQlz4juJwIwE-rpZiM',
    appId: '1:131941295256:web:4fb7289be6c2b89d5d1ced',
    messagingSenderId: '131941295256',
    projectId: 'soganggpt-8a6aa',
    authDomain: 'soganggpt-8a6aa.firebaseapp.com',
    storageBucket: 'soganggpt-8a6aa.appspot.com',
    measurementId: 'G-447PSDTMJK',
  );
}
