# Generated by Django 4.2.11 on 2024-04-01 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='login_cookie',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
