# Generated by Django 4.2.11 on 2024-04-14 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='thread',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
